[PlatformWithOS] Reorganise so the new panel version can be incorporated more easily
Signed-off-by: Christopher Hall <christopherhall.hsw@gmail.com>

diff --git a/PlatformWithOS/Makefile b/PlatformWithOS/Makefile
--- a/PlatformWithOS/Makefile
+++ b/PlatformWithOS/Makefile
@@ -1,31 +1,34 @@
 # Makefile
 
-COG_VERSION ?= NOT-SET
+PANEL_VERSION ?= NOT-SET
 EPD_IO ?= epd_io.h
 
-SUPPORTED_VERSIONS = V1 V2
+SUPPORTED_PANEL_VERSIONS = V110_G1 V230_G2 V231_G2
 
 .PHONY: help
 help:
 	@echo
 	@echo Please use the platform specific targets:
 	@echo
-	@echo COG version setting: add COG_VERSION=V1 or COG_VERSION=V2 to make
-	@echo currently: COG_VERSION=${COG_VERSION}
+	@echo Version Setting:
+	@echo '  G1 options:   PANEL_VERSION=V110_G1'
+	@echo '  G2 options:   PANEL_VERSION=V230_G2  or  PANEL_VERSION=V231_G2'
+	@echo
+	@echo 'currently:      PANEL_VERSION=${PANEL_VERSION}'
 	@echo
 	@echo Custom I/O pin arrangement can be selected, add: EPD_IO=filename.h
 	@echo '(the file will be taken from RaspberryPi or BeagleBone directory as appropriate)'
 	@echo currently: EPD_IO=${EPD_IO}
 	@echo
 	@echo Raspberry Pi:
-	@echo '   make rpi            = build all targets'
-	@echo '   make rpi-install    = install fuse driver in PREFIX'
-	@echo '   make rpi-T          = build only target T'
+	@echo '   $(MAKE) rpi            = build all targets'
+	@echo '   $(MAKE) rpi-install    = install fuse driver in PREFIX'
+	@echo '   $(MAKE) rpi-T          = build only target T'
 	@echo
 	@echo BeagleBone
-	@echo '   make bb             = build all targets'
-	@echo '   make bb-install     = install fuse driver in PREFIX'
-	@echo '   make bb-T           = build only target T'
+	@echo '   $(MAKE) bb             = build all targets'
+	@echo '   $(MAKE) bb-install     = install fuse driver in PREFIX'
+	@echo '   $(MAKE) bb-T           = build only target T'
 	@echo
 	@echo Where T is one of:
 	@echo '    all install remove clean'
@@ -39,38 +42,50 @@ help:
 .PHONY: all
 all: help
 
-.PHONY: cog-error
-cog-error:
+.PHONY: version-error
+version-error:
 	@echo
-	@echo ERROR: COG_VERSION was not set, please set to one of: ${SUPPORTED_VERSIONS}
+	@echo "ERROR:  PANEL_VERSION='${PANEL_VERSION}' is incorrect"
+	@echo
+	@echo please set to one of:
+	@echo
+	@for v in ${SUPPORTED_PANEL_VERSIONS} ; \
+	 do \
+	   echo "  PANEL_VERSION='$${v}'" ; \
+	 done
+	@echo
+	@echo For more information, run:
+	@echo
+	@echo '  $(MAKE) help'
 	@echo
 
 .PHONY: version-check
-ifeq (,$(strip ${COG_VERSION}))
-version-check: cog-error help
-	@false
-else
-ifeq (NOT-SET,$(strip ${COG_VERSION}))
-version-check: cog-error help
-	@false
-else
 version-check:
-	@true
-endif
-endif
+	@flag= ; \
+	 for v in ${SUPPORTED_PANEL_VERSIONS} ; \
+	 do \
+	   [ X"$${v}" = X"${PANEL_VERSION}" ] && flag=x ; \
+	 done ; \
+	 [ -z "$${flag}" ] && $(MAKE) version-error && false || true
 
+
+# Raspberry Pi targets
+# --------------------
 
 .PHONY: rpi raspberrypi
 rpi raspberrypi: version-check
-	make PLATFORM=../RaspberryPi COG_VERSION="${COG_VERSION}" EPD_IO="${EPD_IO}" -C driver-common
+	$(MAKE) PLATFORM=../RaspberryPi PANEL_VERSION="${PANEL_VERSION}" EPD_IO="${EPD_IO}" -C driver-common
 
 rpi-%: version-check
-	make PLATFORM=../RaspberryPi COG_VERSION="${COG_VERSION}" EPD_IO="${EPD_IO}" -C driver-common $*
+	$(MAKE) PLATFORM=../RaspberryPi PANEL_VERSION="${PANEL_VERSION}" EPD_IO="${EPD_IO}" -C driver-common $*
 
+
+# BeagleBone Black targets
+# ------------------------
 
 .PHONY: bb beaglebone
 bb beaglebone: version-check
-	make PLATFORM=../BeagleBone COG_VERSION="${COG_VERSION}" EPD_IO="${EPD_IO}" -C driver-common
+	$(MAKE) PLATFORM=../BeagleBone PANEL_VERSION="${PANEL_VERSION}" EPD_IO="${EPD_IO}" -C driver-common
 
 bb-%: version-check
-	make PLATFORM=../BeagleBone COG_VERSION="${COG_VERSION}" EPD_IO="${EPD_IO}" -C driver-common $*
+	$(MAKE) PLATFORM=../BeagleBone PANEL_VERSION="${PANEL_VERSION}" EPD_IO="${EPD_IO}" -C driver-common $*
